# postgres
#
defaults_development: &defaults_development
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: #postgres
  host: localhost

development:
  database: csc_development
  <<: *defaults_development
